name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout the current branch.
      uses: actions/checkout@v1
    - name: Setup Node.js - 12.x.x
      uses: actions/setup-node@v1
      with:
        node-version: '>=12.10'
    - name: Install project dependencies.
      run: npm install
    - name: Build the project.  
      run: npm run build
    - name: Build artifacts for all supported OSes.
      run: sudo npm run dist-all
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: artifacts
        path: dist/

